### ISSUE TITLE
Show who is on the system complete with IP address.

### ISSUE THREAD

**Issue by pavkar** [jonarani/ICA0007#2]

**Comment by jonarani** [comment]
How much CPU or memory usage does the user take.

**Comment by jonarani** [comment]
https://www.cyberciti.biz/faq/unix-linux-list-current-logged-in-users/

**Comment by jonarani** [comment]
https://linuxize.com/post/usermod-command-in-linux/

**Comment by jonarani** [comment]
https://www.cyberciti.biz/faq/how-to-show-current-logged-in-users-in-linux/
