### ISSUE TITLE
Update user password and send new password to mail

### ISSUE THREAD

**Issue by pavkar** [jonarani/ICA0007#4]

**Comment by pavkar** [comment]
#3

**Comment by pavkar** [comment]
#15

**Comment by jonarani** [comment]
When account password is too old, then generate new password and mail it to user.

**Comment by jonarani** [comment]
1-2 days before sends mail that account needs to be updated.

**Comment by jonarani** [comment]
sudo passwd -e  YYYY-MM-DD peter
