### ISSUE TITLE
Checks when users last modified their passwords

### ISSUE THREAD

**Issue by jonarani** [jonarani/ICA0007#6]
If password have not been changed recently then new one is generated. OR emails will be periodically sent to those users.

**Comment by pavkar** [comment]
https://www.cyberciti.biz/faq/linux-howto-check-user-password-expiration-date-and-time/?__cf_chl_jschl_tk__=b22aa6190551f803553ee8089e5fa9df5270d6bc-1619350358-0-Afp1UcLWxx8JB8NgqXvPuqD7kBZQ7o1Xlb7v5i69J4PUkKyDP3wadPmW_TDPIpae2ePlQZK9sqNxidLj1vTxdGDOjzXM4TV7cUdOh6uDbXVQ2xH9lTM6HiGsORQeGZvw3M9-BaYdRjGmGl-6Xd-YEOZfu6x1D4WXG2oLzd2jWrnRvA2ixxGzkEsEQ7QeatCsRc4TNHZkgl5dFnov9GDXjCcFZe1hvBjN7NnwGUWQrMkZewnTXjif26iSgiDnyyFzu7TSowss1QPKtFIShzeUvy7jFIPiZ5orus376Y4vU2aSc5Fx6tgkmP7exYVJU-zttedFcvRV7zvgEh2NiLLRhzvjbl3KDKGO-pFVlsvHFKx1STkHj4_-GjitfKZWVqS6AaMjMYCOr2qndDGrZhgt2jNs00MHAORlrUXgyt3mrB3PclhwTUY12AW40d18imkeYyqrLLwibqSTrJub20XBFK2XPLJmpFyYy3cYpr9d9kuMeS-t720D9_cfUFw9R7IZtj1w8zHzC9kFeHZhavmM2uM

**Comment by pavkar** [comment]
Checks all passwords expiry dates. If never then checks date of creation and adds expiry date + 2 months.

**Comment by pavkar** [comment]
Sends mail that password has expiry date

**Comment by jonarani** [comment]
IF never and password not changed recently then generate new password and mail it
