### ISSUE TITLE
Check active ssh keys

### ISSUE THREAD

**Issue by pavkar** [jonarani/ICA0007#7]
- [ ] Check when last modified

**Comment by pavkar** [comment]
https://unix.stackexchange.com/questions/82489/how-to-check-which-ssh-keys-are-currently-active

**Comment by pavkar** [comment]
eval 'ssh-agent'
SSH_AUTH_SOCK=/tmp/ssh-oXNeYpRB8z2I/agent.17746; export SSH_AUTH_SOCK;
SSH_AGENT_PID=17747; export SSH_AGENT_PID;
echo Agent pid 17747;

**Comment by jonarani** [comment]
Needs investigation

**Comment by pavkar** [comment]
Checking ssh key-s that are connected
