### ISSUE TITLE
Searches files that are 777 or that are very old.

### ISSUE THREAD

**Issue by jonarani** [jonarani/ICA0007#8]
Displays them or writes to file? Can be configured?

**Comment by pavkar** [comment]
https://superuser.com/questions/71041/find-all-files-on-server-with-777-permissions

**Comment by jonarani** [comment]
Inputs: path, other permissions, age, and wanted permission

**Comment by jonarani** [comment]
nice to have: https://askubuntu.com/questions/581290/what-is-the-first-number-for-in-a-4-number-chmod-argument-such-as-chmod-4555

Special bit
